# Ouvre un bloc de configuration pour un site Nginx.
server {
    # Nginx écoute sur le port 80.
    listen 80;
    # Accepte n'importe quel nom de serveur.
    server_name _;
    # Répertoire racine où se trouvent les fichiers Angular compilés.
    root /usr/share/nginx/html;
    # Fichier servi par défaut si aucun autre n'est demandé.
    index index.html;

    # Gestion de toutes les routes du front Angular.
    location / {
        # Sert le fichier demandé, sinon revient vers index.html pour le routing SPA.
        try_files $uri $uri/ /index.html;
    }
}